// -----------------------------------------------------------------------------
// rope_engine_tb.sv — Self-checking testbench for rope_engine.
//
// Replays vectors generated by python/rope_golden.py and checks bit-equality
// on every output beat. Vectors live in tb/vectors/ (run gen_vectors first).
//
// Pass criterion: every output element matches the golden exactly. Saturation
// and pipeline alignment are exercised end-to-end.
//
// Run with Icarus:
//     iverilog -g2012 -o sim_rope_tb \
//         rtl/rope_rotate_pe.sv rtl/rope_sincos_lut.sv rtl/rope_engine.sv \
//         tb/rope_engine_tb.sv
//     (cd tb/vectors && vvp ../../sim_rope_tb)
// -----------------------------------------------------------------------------
`timescale 1ns/1ps
`default_nettype none

`include "vectors/config.vh"

module rope_engine_tb;
    localparam int DATA_WIDTH      = `CFG_DATA_WIDTH;
    localparam int HEAD_DIM        = `CFG_HEAD_DIM;
    localparam int MAX_SEQ_LEN     = `CFG_MAX_SEQ_LEN;
    localparam int N_TESTS         = `CFG_N_TESTS;
    localparam int POS_WIDTH       = `CFG_POS_WIDTH;
    localparam int PAIRS_PER_CYCLE = 4;
    localparam int N_PAIRS         = HEAD_DIM / 2;
    localparam int BEATS_PER_VEC   = N_PAIRS / PAIRS_PER_CYCLE;

    // ---- Clock / reset ----
    reg clk = 0;
    always #1.25 clk = ~clk;              // 400 MHz
    reg rst_n = 0;

    // ---- DUT ports ----
    reg                                       s_valid;
    wire                                      s_ready;
    reg  [PAIRS_PER_CYCLE*2*DATA_WIDTH-1:0]   s_data;
    reg  [POS_WIDTH-1:0]                      s_position;
    reg                                       s_last;

    wire                                      m_valid;
    wire [PAIRS_PER_CYCLE*2*DATA_WIDTH-1:0]   m_data;
    wire                                      m_last;

    rope_engine #(
        .DATA_WIDTH     (DATA_WIDTH),
        .HEAD_DIM       (HEAD_DIM),
        .MAX_SEQ_LEN    (MAX_SEQ_LEN),
        .PAIRS_PER_CYCLE(PAIRS_PER_CYCLE),
        .POS_WIDTH      (POS_WIDTH)
    ) dut (
        .clk        (clk),
        .rst_n      (rst_n),
        .s_valid    (s_valid),
        .s_ready    (s_ready),
        .s_data     (s_data),
        .s_position (s_position),
        .s_last     (s_last),
        .m_valid    (m_valid),
        .m_ready    (1'b1),
        .m_data     (m_data),
        .m_last     (m_last)
    );

    // ---- Vector storage ----
    reg [DATA_WIDTH-1:0] stim_mem     [0:N_TESTS*HEAD_DIM-1];
    reg [DATA_WIDTH-1:0] expected_mem [0:N_TESTS*HEAD_DIM-1];
    reg [POS_WIDTH-1:0]  position_mem [0:N_TESTS-1];

    // ---- Scoreboard ----
    integer errors  = 0;
    integer beats_collected = 0;
    integer tokens_collected = 0;

    // ---- Output monitor: checks each m_valid beat against expected ----
    always @(posedge clk) begin
        if (m_valid) begin
            integer beat_idx_in_vec;
            integer token_idx;
            integer base_elem;
            beat_idx_in_vec = beats_collected % BEATS_PER_VEC;
            token_idx       = beats_collected / BEATS_PER_VEC;
            base_elem       = token_idx * HEAD_DIM
                            + beat_idx_in_vec * PAIRS_PER_CYCLE * 2;

            for (int lane = 0; lane < PAIRS_PER_CYCLE * 2; lane++) begin
                logic signed [DATA_WIDTH-1:0] got;
                logic signed [DATA_WIDTH-1:0] exp;
                got = m_data[lane*DATA_WIDTH +: DATA_WIDTH];
                exp = expected_mem[base_elem + lane];
                if (got !== exp) begin
                    $display("[FAIL] test=%0d lane=%0d got=%0d exp=%0d (h%h vs h%h)",
                             token_idx, lane, got, exp, got, exp);
                    errors = errors + 1;
                end
            end

            beats_collected = beats_collected + 1;
            if (m_last) tokens_collected = tokens_collected + 1;
        end
    end

    // ---- Stimulus driver ----
    task automatic drive_vector(input integer test_idx);
        integer base_elem;
        base_elem = test_idx * HEAD_DIM;
        for (int b = 0; b < BEATS_PER_VEC; b++) begin
            @(posedge clk);
            s_valid    <= 1'b1;
            s_position <= position_mem[test_idx];
            s_last     <= (b == BEATS_PER_VEC - 1);
            for (int lane = 0; lane < PAIRS_PER_CYCLE * 2; lane++) begin
                s_data[lane*DATA_WIDTH +: DATA_WIDTH]
                    <= stim_mem[base_elem + b*PAIRS_PER_CYCLE*2 + lane];
            end
        end
        @(posedge clk);
        s_valid <= 1'b0;
        s_last  <= 1'b0;
    endtask

    // ---- Main ----
    initial begin
        // Waveform dump (view with: gtkwave rope_engine_tb.vcd)
        $dumpfile("rope_engine_tb.vcd");
        $dumpvars(0, rope_engine_tb);

        $display("-------------------------------------------------------");
        $display("rope_engine_tb: HEAD_DIM=%0d PAIRS/CYC=%0d TESTS=%0d",
                 HEAD_DIM, PAIRS_PER_CYCLE, N_TESTS);
        $display("-------------------------------------------------------");

        // Load vectors (run from tb/vectors/ so relative paths work)
        $readmemh("stim.hex",      stim_mem);
        $readmemh("expected.hex",  expected_mem);
        $readmemh("positions.hex", position_mem);

        // Reset
        s_valid = 0; s_last = 0; s_data = '0; s_position = '0;
        repeat (5) @(posedge clk);
        rst_n = 1;
        repeat (5) @(posedge clk);

        // Drive all test vectors back-to-back
        for (int t = 0; t < N_TESTS; t++) begin
            drive_vector(t);
        end

        // Drain the pipeline
        repeat (20) @(posedge clk);

        $display("-------------------------------------------------------");
        $display("TOKENS_COLLECTED = %0d / %0d", tokens_collected, N_TESTS);
        $display("ERRORS           = %0d", errors);
        if (errors == 0 && tokens_collected == N_TESTS)
            $display("RESULT: PASS (%0d/%0d tests, 0 bit-errors)", N_TESTS, N_TESTS);
        else
            $display("RESULT: FAIL");
        $display("-------------------------------------------------------");

        $finish;
    end

    // Watchdog
    initial begin
        #200000;
        $display("RESULT: TIMEOUT");
        $finish;
    end

endmodule

`default_nettype wire
